steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          -t us-central1-docker.pkg.dev/test-ecommerce-462704/ecommerce-api/ecommerce-api:$SHORT_SHA \
          --build-arg DB_HOST=$$DB_HOST \
          --build-arg DB_PORT=$$DB_PORT \
          --build-arg DB_USER=$$DB_USER \
          --build-arg DB_PASSWORD=$$DB_PASSWORD \
          --build-arg DB_NAME=$$DB_NAME \
          --build-arg SSL_MODE=$$SSL_MODE \
          --build-arg USER_SECRET=$$USER_SECRET \
          --build-arg SHOP_SECRET=$$SHOP_SECRET \
          .

    secretEnv:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SSL_MODE
      - USER_SECRET
      - SHOP_SECRET

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/test-ecommerce-462704/ecommerce-api/ecommerce-api:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy ecommerce-api \
          --image us-central1-docker.pkg.dev/test-ecommerce-462704/ecommerce-api/ecommerce-api:$SHORT_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars DB_HOST=$$DB_HOST,DB_PORT=$$DB_PORT,DB_USER=$$DB_USER,DB_PASSWORD=$$DB_PASSWORD,DB_NAME=$$DB_NAME,SSL_MODE=$$SSL_MODE,USER_SECRET=$$USER_SECRET,SHOP_SECRET=$$SHOP_SECRET

    secretEnv:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SSL_MODE
      - USER_SECRET
      - SHOP_SECRET

availableSecrets:
  secretManager:
    - versionName: projects/783881626577/secrets/DB_HOST/versions/1
      env: DB_HOST
    - versionName: projects/783881626577/secrets/DB_PORT/versions/1
      env: DB_PORT
    - versionName: projects/783881626577/secrets/DB_USER/versions/1
      env: DB_USER
    - versionName: projects/783881626577/secrets/DB_PASSWORD/versions/1
      env: DB_PASSWORD
    - versionName: projects/783881626577/secrets/DB_NAME/versions/1
      env: DB_NAME
    - versionName: projects/783881626577/secrets/SSL_MODE/versions/1
      env: SSL_MODE
    - versionName: projects/783881626577/secrets/USER_SECRET/versions/1
      env: USER_SECRET
    - versionName: projects/783881626577/secrets/SHOP_SECRET/versions/1
      env: SHOP_SECRET

images:
  - us-central1-docker.pkg.dev/test-ecommerce-462704/ecommerce-api/ecommerce-api:$SHORT_SHA

timeout: 1200s


options:
  logging: CLOUD_LOGGING_ONLY
