services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_ecommerce_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ecommerce-network

  app:
    build: .
    container_name: ecommerce-api
    depends_on:
      - postgres
    ports:
      - "1323:1323"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: ecommerce
    networks:
      - ecommerce-network
    restart: always

volumes:
  postgres_ecommerce_db:

networks:
  ecommerce-network:
    driver: bridge
