services:
  postgres:
    image: postgres:16
    container_name: ecommerce-api
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_ecommerce_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_ecommerce_db:
